GIS:
  GIS_USERNAME: ""
  GIS_PASSWORD: ""
  SERVER: "arthurhouftps.pps.eosdis.nasa.gov"
  NEAR_REALTIME_SERVER: "jsimpsonftps.pps.eosdis.nasa.gov"

EARTHDATA:
  EARTHDATA_USERNAME: ""
  EARTHDATA_PASSWORD: ""

HIMAWARI:
  FTP_USER: ""
  FTP_PASS: ""
  FTP_HOST: "ftp.ptree.jaxa.jp"

MODIS:
  TOKEN: ""

VIIRS:
  TOKEN: ""

ECMWF:
  TOKEN: ""
