GIS:
  GIS_USERNAME: "tr.hoanganh1124work@gmail.com"
  GIS_PASSWORD: "tr.hoanganh1124work@gmail.com"
  SERVER: "arthurhouftps.pps.eosdis.nasa.gov"
  NEAR_REALTIME_SERVER: "jsimpsonftps.pps.eosdis.nasa.gov"

EARTHDATA:
  EARTHDATA_USERNAME: "sfatew"
  EARTHDATA_PASSWORD: "Hoanganh1124work@"

HIMAWARI:
  FTP_USER: "tr.hoanganh1124work_gmail.com"
  FTP_PASS: "SP+wari8"
  FTP_HOST: "ftp.ptree.jaxa.jp"

MODIS:
  TOKEN: "eyJ0eXAiOiJKV1QiLCJvcmlnaW4iOiJFYXJ0aGRhdGEgTG9naW4iLCJzaWciOiJlZGxqd3RwdWJrZXlfb3BzIiwiYWxnIjoiUlMyNTYifQ.eyJ0eXBlIjoiVXNlciIsInVpZCI6InNmYXRldyIsImV4cCI6MTc4NDc3NzE1MSwiaWF0IjoxNzc5NTkzMTUxLCJpc3MiOiJodHRwczovL3Vycy5lYXJ0aGRhdGEubmFzYS5nb3YiLCJpZGVudGl0eV9wcm92aWRlciI6ImVkbF9vcHMiLCJhY3IiOiJlZGwiLCJhc3N1cmFuY2VfbGV2ZWwiOjN9.3Em8pVFvV8yN8wEI9FVPLldJik0Fo74vT665vfdH69dkzo5nNLphHCW8G-B3vqlMsq-7q3X-GFWwo0c5LS2Xv6EceHRflJTQTns457gLMXxlHZpYEgnk20lzFqf718pvKvKRFyJrOxkUxmVjiDlCLqubakaXhZjdtpkbOlHutELfMVIW3O9UcC3it9GSbBszWf6SPx9ofVIOwY7R-6BbJXb5a_7-Kq4kbr_eQJTiG1yn5HGBZHNPixYpICcg6DBOfL52OLnzyT9qN7tlaMdC4NECubmmMRw-9JbObvSIks-CxjZjbNTIPpve-KiXijSIIkk5IOmVGh_k95HhBhUuKw"

VIIRS:
  TOKEN: "eyJ0eXAiOiJKV1QiLCJvcmlnaW4iOiJFYXJ0aGRhdGEgTG9naW4iLCJzaWciOiJlZGxqd3RwdWJrZXlfb3BzIiwiYWxnIjoiUlMyNTYifQ.eyJ0eXBlIjoiVXNlciIsInVpZCI6InNmYXRldyIsImV4cCI6MTc4NDc3NzE1MSwiaWF0IjoxNzc5NTkzMTUxLCJpc3MiOiJodHRwczovL3Vycy5lYXJ0aGRhdGEubmFzYS5nb3YiLCJpZGVudGl0eV9wcm92aWRlciI6ImVkbF9vcHMiLCJhY3IiOiJlZGwiLCJhc3N1cmFuY2VfbGV2ZWwiOjN9.3Em8pVFvV8yN8wEI9FVPLldJik0Fo74vT665vfdH69dkzo5nNLphHCW8G-B3vqlMsq-7q3X-GFWwo0c5LS2Xv6EceHRflJTQTns457gLMXxlHZpYEgnk20lzFqf718pvKvKRFyJrOxkUxmVjiDlCLqubakaXhZjdtpkbOlHutELfMVIW3O9UcC3it9GSbBszWf6SPx9ofVIOwY7R-6BbJXb5a_7-Kq4kbr_eQJTiG1yn5HGBZHNPixYpICcg6DBOfL52OLnzyT9qN7tlaMdC4NECubmmMRw-9JbObvSIks-CxjZjbNTIPpve-KiXijSIIkk5IOmVGh_k95HhBhUuKw"

ECMWF:
  TOKEN: "56338527-6c4a-4b49-b6c2-14213c2eefd5"
  