services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  webserver:
    build: .
    image: airflow:v3
    restart: always
    container_name: webserver
    entrypoint: ["/opt/airflow/entrypoint.sh"]
    command: ["airflow", "webserver"]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__API__SECRET_KEY: this_is_a_very_secured_key
      AIRFLOW__WEBSERVER__SECRET_KEY: this_is_a_very_secured_key
      AIRFLOW_CONN_SPARK_DEFAULT: spark://spark-master:7077?deploy_mode=client
      AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
    volumes:
      - ./dags:/opt/airflow/dags
      - ../AERONET:/opt/airflow/dags/AERONET
      - ../Himawari:/opt/airflow/dags/Himawari
      - ../Masterdata:/opt/airflow/dags/Masterdata
      - ../Modis:/opt/airflow/dags/Modis
      - ../VIIRS:/opt/airflow/dags/VIIRS
      - ../config:/opt/airflow/dags/config
      - ../GADM_Vietnam:/opt/airflow/dags/GADM_Vietnam
      - airflow_logs:/opt/airflow/logs
      - /home/slow_data:/home/slow_data
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    image: airflow:v3
    restart: always
    container_name: scheduler
    hostname: scheduler
    entrypoint: ["/opt/airflow/entrypoint.sh"]
    command: ["airflow", "scheduler"]
    depends_on:
      webserver:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__API__SECRET_KEY: this_is_a_very_secured_key
      AIRFLOW__WEBSERVER__SECRET_KEY: this_is_a_very_secured_key
      AIRFLOW_CONN_SPARK_DEFAULT: spark://spark-master:7077?deploy_mode=client
      AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth

    volumes:
      - ./dags:/opt/airflow/dags
      - ../AERONET:/opt/airflow/dags/AERONET
      - ../Himawari:/opt/airflow/dags/Himawari
      - ../Masterdata:/opt/airflow/dags/Masterdata
      - ../Modis:/opt/airflow/dags/Modis
      - ../VIIRS:/opt/airflow/dags/VIIRS
      - ../config:/opt/airflow/dags/config
      - ../GADM_Vietnam:/opt/airflow/dags/GADM_Vietnam
      - airflow_logs:/opt/airflow/logs
      - /home/slow_data:/home/slow_data

networks:
  default:
    name: Airqua_net

volumes:
  postgres_data:
  airflow_logs: